theme: jekyll-theme-architect

# Site Settings
locale: "en-US"
title: "Catena-X DevSecOps Tooling"
title_separator: "-"
subtitle: "DevSecOps Tooling"
name: ""
description: "You are a Catena-X developer? Here you can find all the necessary information to use our central standards and tools"
